repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.3.5"
    hooks:
      - id: ruff-format
      - id: ruff
        args:
          - "--exit-non-zero-on-fix"

  - repo: https://github.com/pycqa/pylint
    # Cannot be replaced by ruff until https://github.com/astral-sh/ruff/issues/970 is closed
    rev: "v3.1.0"
    hooks:
      - id: pylint
        additional_dependencies:
          - pytest
          - pydantic

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.9.0"
    hooks:
      - id: mypy
        additional_dependencies:
          - pytest
          - pydantic

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
