services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: ".env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  database_service:
    build: ./database-service
    ports:
      - "8000:8000"
    env_file: ".env"

  text_to_sql_service:
    build: ./text-to-sql-service
    ports:
      - "5001:5001"
    env_file: ".env"

  user_interface_service:
    build: ./user-interface-service
    ports:
      - "8501:8501"
    env_file: ".env"
